stages:
  - test
  - deploy

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

#
# Templates
#

.test_template:
  stage: test
  image: docker:stable
  allow_failure: true
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - apk add py-pip
    - apk add python3-dev libffi-dev openssl-dev gcc libc-dev make bash
    - pip install docker-compose
    - mkdir results
  script:
    - cd docker-compose
    - if [ -z "$ASSET" ]; then ASSET_ARG=""; else export ASSET_ARG="-a docker-compose-$ASSET.yml"; fi
    - ./run.sh -s docker-compose-$SERVER.yml -c docker-compose-$CLIENT.yml -d $SERVER+$CLIENT $ASSET_ARG -u $CI_JOB_URL > ../results/${SERVER}+${CLIENT}.json
  services:
    - docker:dind
  artifacts:
    paths:
      - results/
    when: always

.pages_template:
  stage: deploy
  image: monachus/hugo:v0.74.3
  script:
    - apt update && apt install jq -y
    - mkdir -p site/data results
    - "cat results/*.json | jq -s 'map({(.name|tostring): .}) | add' | tee site/data/jobs.json"
    - cd site && hugo
    - mv public ../public
  variables:
    HUGO_PARAMS_commit_hash: $CI_COMMIT_SHORT_SHA
    HUGO_PARAMS_commit_url: $CI_PROJECT_URL/-/commit/$CI_COMMIT_SHA
    HUGO_PARAMS_pipeline_id: $CI_PIPELINE_ID
    HUGO_PARAMS_pipeline_url: $CI_PIPELINE_URL
  artifacts:
    paths:
      - public

.remote_downloader_template:
  variables:
    BAZEL_ARGS: "--remote_cache=grpc://frontend:8980 --experimental_remote_downloader=grpc://asset:8979"

#
# Bazel client
#

test_buildbarn_bazel:
  extends: .test_template
  variables:
    SERVER: buildbarn
    CLIENT: bazel

test_buildfarm_bazel:
  extends: .test_template
  variables:
    SERVER: buildfarm
    CLIENT: bazel

test_buildgrid_bazel:
  extends: .test_template
  variables:
    SERVER: buildgrid
    CLIENT: bazel

#
# Bazel client w/ remote asset
#

test_buildbarn_bazel_asset_hub:
  extends:
    - .test_template
    - .remote_downloader_template
  variables:
    SERVER: buildbarn
    CLIENT: bazel
    ASSET: asset_hub

test_buildfarm_bazel_asset_hub:
  extends:
    - .test_template
    - .remote_downloader_template
  variables:
    SERVER: buildfarm
    CLIENT: bazel
    ASSET: asset_hub

test_buildgrid_bazel_asset_hub:
  extends:
    - .test_template
    - .remote_downloader_template
  variables:
    SERVER: buildgrid
    CLIENT: bazel
    ASSET: asset_hub

#
# Goma client
#

test_buildbarn_goma:
  extends: .test_template
  variables:
    SERVER: buildbarn
    CLIENT: goma

test_buildfarm_goma:
  extends: .test_template
  variables:
    SERVER: buildfarm
    CLIENT: goma

test_buildgrid_goma:
  extends: .test_template
  variables:
    SERVER: buildgrid
    CLIENT: goma

#
# Recc client
#

test_buildbarn_recc:
  extends: .test_template
  variables:
    SERVER: buildbarn
    CLIENT: recc

test_buildfarm_recc:
  extends: .test_template
  variables:
    SERVER: buildfarm
    CLIENT: recc

test_buildgrid_recc:
  extends: .test_template
  variables:
    SERVER: buildgrid
    CLIENT: recc

#
# Pages
#

# a stopgap to simulate review apps, allows us to quickly see
# the status of an MR before merging it
# see: https://gitlab.com/gitlab-org/gitlab/-/issues/16907#note_214936412
pages:review:
  extends: .pages_template
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
  variables:
    HUGO_BASEURL: https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/index.html

# build static gitlab page for displaying remote-apis-testing results
pages:
  extends: .pages_template
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  variables:
    HUGO_BASEURL: $CI_PAGES_URL
