stages:
  - test
  - deploy

.test_template: &test
  stage: test
  allow_failure: true
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - apk add py-pip
    - apk add python3-dev libffi-dev openssl-dev gcc libc-dev make bash
    - pip install docker-compose
  script:
    - cd docker-compose
    - echo "export COLOR="critical" STATUS="failed"" > ../result-vars
    - if [ -z "$ASSET" ]; then ASSET_ARG=""; else export ASSET_ARG="-a docker-compose-$ASSET.yml"; fi
    - ./run.sh -s docker-compose-$SERVER.yml -c docker-compose-$CLIENT.yml $ASSET_ARG
    - echo "export COLOR="success" STATUS="success"" > ../result-vars
  after_script:
    - . ./result-vars
    - mkdir -p badges
    - curl -o badges/${SERVER}-${CLIENT}${ASSET:+-$ASSET}-deployed.svg https://img.shields.io/badge/${SERVER}_${CLIENT}${ASSET:+_$ASSET}-${STATUS}_${CI_COMMIT_SHORT_SHA}-${COLOR}.svg
  image: docker:stable
  services:
    - docker:dind
  artifacts:
    name: pages
    paths:
      - badges/
    when: always

### Bazel client

.remote_downloader_template: &bazel_remote_downloader
  variables: &bazel_remote_downloader_vars
    BAZEL_ARGS: "--remote_cache=grpc://frontend:8980 --experimental_remote_downloader=grpc://asset:8979"

test_buildbarn_bazel:
  <<: *test
  variables:
    SERVER: buildbarn
    CLIENT: bazel

test_buildbarn_bazel_asset_hub:
  <<: *test
  variables:
    <<: *bazel_remote_downloader_vars
    SERVER: buildbarn
    CLIENT: bazel
    ASSET: asset_hub

test_buildfarm_bazel:
  <<: *test
  variables:
    SERVER: buildfarm
    CLIENT: bazel

test_buildfarm_bazel_asset_hub:
  <<: *test
  variables:
    <<: *bazel_remote_downloader_vars
    SERVER: buildfarm
    CLIENT: bazel
    ASSET: asset_hub


test_buildgrid_bazel:
  <<: *test
  variables:
    SERVER: buildgrid
    CLIENT: bazel

test_buildgrid_bazel_asset_hub:
  <<: *test
  variables:
    <<: *bazel_remote_downloader_vars
    SERVER: buildgrid
    CLIENT: bazel
    ASSET: asset_hub

### Goma client

test_buildbarn_goma:
  <<: *test
  variables:
    SERVER: buildbarn
    CLIENT: goma

test_buildfarm_goma:
  <<: *test
  variables:
    SERVER: buildfarm
    CLIENT: goma

test_buildgrid_goma:
  <<: *test
  variables:
    SERVER: buildgrid
    CLIENT: goma

### Recc client

test_buildbarn_recc:
  <<: *test
  variables:
    SERVER: buildbarn
    CLIENT: recc

test_buildfarm_recc:
  <<: *test
  variables:
    SERVER: buildfarm
    CLIENT: recc

test_buildgrid_recc:
  <<: *test
  variables:
    SERVER: buildgrid
    CLIENT: recc

pages:
  stage: deploy
  script:
    - mkdir public
    - cp badges/* public/
  artifacts:
    name: pages
    paths:
      - public/
      - badges/
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
