stages:
    - test

.test_template: &test
  stage: test
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - apk add py-pip
    - apk add python3-dev libffi-dev openssl-dev gcc libc-dev make bash
    - pip install docker-compose
  script:
    - cd docker-compose
    - ./run.sh -s $SERVER -c $CLIENT
  image: docker:stable
  services:
    - docker:dind

### Bazel client

test_buildbarn_bazel:
  <<: *test
  variables:
    SERVER: docker-compose-buildbarn.yml
    CLIENT: docker-compose-bazel.yml

test_buildfarm_bazel:
  <<: *test
  variables:
    SERVER: docker-compose-buildfarm.yml
    CLIENT: docker-compose-bazel.yml

test_buildgrid_bazel:
  <<: *test
  variables:
    SERVER: docker-compose-buildgrid.yml
    CLIENT: docker-compose-bazel.yml

### Goma client

test_buildbarn_goma:
  <<: *test
  variables:
    SERVER: docker-compose-buildbarn.yml
    CLIENT: docker-compose-goma.yml

test_buildfarm_goma:
  <<: *test
  variables:
    SERVER: docker-compose-buildfarm.yml
    CLIENT: docker-compose-goma.yml

test_buildgrid_goma:
  <<: *test
  variables:
    SERVER: docker-compose-buildgrid.yml
    CLIENT: docker-compose-goma.yml

### Recc client

test_buildbarn_recc:
  <<: *test
  variables:
    SERVER: docker-compose-buildbarn.yml
    CLIENT: docker-compose-recc.yml

test_buildfarm_recc:
  <<: *test
  variables:
    SERVER: docker-compose-buildfarm.yml
    CLIENT: docker-compose-recc.yml

test_buildgrid_recc:
  <<: *test
  variables:
    SERVER: docker-compose-buildgrid.yml
    CLIENT: docker-compose-recc.yml    