stages:
  - test
  - deploy

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

#
# Templates
#

.test_template:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
  image: docker:stable
  allow_failure: true
  before_script:
    - apk add --update curl && rm -rf /var/cache/apk/*
    - apk add py-pip
    - apk add python3-dev libffi-dev openssl-dev gcc libc-dev make bash
    - pip install cryptography==3.3.2 docker-compose jinja2 ruamel.yaml
    - mkdir results
  script:
    - cd docker-compose
    - if [ -z "$ASSET" ]; then ASSET_ARG=""; else export ASSET_ARG="-a docker-compose-$ASSET.yml"; fi
    - ./run.sh -g -s docker-compose-$SERVER.yml -c docker-compose-$CLIENT.yml -d $SERVER+$CLIENT $ASSET_ARG -u $CI_JOB_URL > ../results/${SERVER}+${CLIENT}.json
  services:
    - docker:dind
  artifacts:
    paths:
      - results/
    when: always

.pages_template:
  stage: deploy
  image: monachus/hugo:v0.74.3
  script:
    - apt update && apt install jq -y
    - mkdir -p site/data results
    - "cat results/*.json | jq -s 'map({(.name|tostring): .}) | add' | tee site/data/jobs.json"
    - cd site && hugo
    - mv public ../public
  variables:
    HUGO_PARAMS_commit_hash: $CI_COMMIT_SHORT_SHA
    HUGO_PARAMS_commit_url: $CI_PROJECT_URL/-/commit/$CI_COMMIT_SHA
    HUGO_PARAMS_pipeline_id: $CI_PIPELINE_ID
    HUGO_PARAMS_pipeline_url: $CI_PIPELINE_URL
  artifacts:
    paths:
      - public

.remote_downloader_template:
  variables:
    BAZEL_ARGS: "--remote_cache=grpc://frontend:8980 --experimental_remote_downloader=grpc://asset:8979"

#
# Bazel client
#

test_buildbarn_bazel:
  extends: .test_template
  variables:
    SERVER: buildbarn
    CLIENT: bazel

test_buildfarm_bazel:
  extends: .test_template
  variables:
    SERVER: buildfarm
    CLIENT: bazel

test_buildgrid_bazel:
  extends: .test_template
  variables:
    SERVER: buildgrid
    CLIENT: bazel

#
# Bazel client w/ remote asset
#

test_buildbarn_bazel_remote_asset:
  extends:
    - .test_template
    - .remote_downloader_template
  variables:
    SERVER: buildbarn
    CLIENT: bazel
    ASSET: remote_asset

test_buildfarm_bazel_remote_asset:
  extends:
    - .test_template
    - .remote_downloader_template
  variables:
    SERVER: buildfarm
    CLIENT: bazel
    ASSET: remote_asset

test_buildgrid_bazel_remote_asset:
  extends:
    - .test_template
    - .remote_downloader_template
  variables:
    SERVER: buildgrid
    CLIENT: bazel
    ASSET: remote_asset

#
# Goma client
#

test_buildbarn_goma:
  extends: .test_template
  variables:
    SERVER: buildbarn
    CLIENT: goma

test_buildfarm_goma:
  extends: .test_template
  variables:
    SERVER: buildfarm
    CLIENT: goma

test_buildgrid_goma:
  extends: .test_template
  variables:
    SERVER: buildgrid
    CLIENT: goma

#
# Recc client
#

test_buildbarn_recc:
  extends: .test_template
  variables:
    SERVER: buildbarn
    CLIENT: recc

test_buildfarm_recc:
  extends: .test_template
  variables:
    SERVER: buildfarm
    CLIENT: recc

test_buildgrid_recc:
  extends: .test_template
  variables:
    SERVER: buildgrid
    CLIENT: recc

#
# Pants client
#

test_buildbarn_pants:
  extends: .test_template
  variables:
    SERVER: buildbarn
    CLIENT: pants

test_buildfarm_pants:
  extends: .test_template
  variables:
    SERVER: buildfarm
    CLIENT: pants

test_buildgrid_pants:
  extends: .test_template
  variables:
    SERVER: buildgrid
    CLIENT: pants

#
# Automated Updates
#

# Auto updates require that two environment variables be set up in GitLab CI Settings
# These should both be set up as 'file' variables (ie when CI runs, the value supplied
#   in settings will be stored in a temporary file, and the variable will resolve to the
#   name of the temp file).
# For security reasons, these variables should be set as "MASKED" and "PROTECTED"
#
# BOT_ACCESS_TOKEN should contain an access token with API permissions
# BOT_SSH_KEY should contain an rsa private key
#
# Both of these should be up to date credentials, granting access to the GitLab account
#   called "remote-apis-testing-bot". The bot account is currently managed by Codethink,
#   and is registered with the address "remote-apis-testing-bot@codethink.co.uk".
#
auto_update_refs_and_generate_merge_requests:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_TASK == "auto-update"'
  allow_failure: true
  image: python
  before_script:
    - pip3 install requests
    - chmod 600 $BOT_SSH_KEY
    - git config --global user.name "bot"
    - git config --global user.email "remote-apis-testing-bot@codethink.co.uk"
    - git remote set-url origin "git@${CI_SERVER_HOST}:${CI_PROJECT_PATH}.git"
    - export GIT_SSH_COMMAND="ssh -o 'IdentitiesOnly yes' -o 'StrictHostKeyChecking no' -i $BOT_SSH_KEY"
    - cd auto-updater
  script:
    - python3 check_for_open_automated_merge_requests.py "${CI_PROJECT_ID}" "${CI_API_V4_URL}"
    - OLD_COMMIT="$(git log -n1 --format=%H)"
    - python3 update_refs_in_docker_compose_yaml.py
    - NEW_COMMIT="$(git log -n1 --format=%H)"
    - >
      if [ "${OLD_COMMIT}" != "${NEW_COMMIT}" ];
      then python3 create_merge_request.py "${CI_PROJECT_ID}" "${CI_API_V4_URL}" "${BOT_ACCESS_TOKEN}";
      else echo "Checks complete. No need to create a new branch or Merge Request.";
           echo "Everything is already up to date.";
      fi

#
# Pages
#

# a stopgap to simulate review apps, allows us to quickly see
# the status of an MR before merging it
# see: https://gitlab.com/gitlab-org/gitlab/-/issues/16907#note_214936412
pages:review:
  extends: .pages_template
  rules:
    - if: '$CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE != "schedule"'
  variables:
    HUGO_BASEURL: https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/index.html

# build static gitlab page for displaying remote-apis-testing results
pages:
  extends: .pages_template
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE != "schedule"'
  variables:
    HUGO_BASEURL: $CI_PAGES_URL
