languageCode = "en-us"
theme = "casper"
title = "REAPIs Testing"

[params]
description = "A compatability matrix between implementations of the Remote-Execution API."
gitlab = "https://gitlab.com/remote-apis-testing/remote-apis-testing"
mainSections = ["post"]

[menu]
[[menu.main]]
identifier = "repository"
name = "Repository"
url = "https://gitlab.com/remote-apis-testing/remote-apis-testing"
weight = 10

[outputs]
home = ["HTML", "RSS", "HEADERS"]

[mediaTypes]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]
[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
