apiVersion: batch/v1
kind: Job
metadata:
  name: build-abseil
  namespace: buildgrid
spec:
  template:
    metadata:
      name: build-abseil
    spec:
      containers:
      - name: build-abseil
        image: remoteapistesting/bazel-build-buildgrid:latest
        command:
         - /bin/bash
         - -c
         - /bin/bazel-build-wrapper https://github.com/abseil/abseil-cpp master --spawn_strategy=remote --genrule_strategy=remote --remote_executor=grpc://buildgrid-stack:50051 --remote_instance_name= //absl/...
      restartPolicy: Never
  backoffLimit: 0
