apiVersion: batch/v1
kind: Job
metadata:
  name: build-autotools
  namespace: buildgrid
spec:
  template:
    metadata:
      name: build-autotools
    spec:
      initContainers:
        - name: pull-repo
          image: alpine/git
          args:
            - clone
            - --single-branch
            - --
            - https://gitlab.com/BuildStream/buildstream.git
            - /repo
          volumeMounts:
            - name: bst-repo
              mountPath: /repo
      containers:
      - name: build-autotools
        image: buildstream/buildstream:nightly
        command: ["/bin/bash", "-c"]
        args:
         - cd /project;
           cat /server-conf/project-server.conf | tee -a project.conf;
           bst --debug --verbose build hello.bst
        volumeMounts:
          - name: bst-repo
            mountPath: /project
            subPath: doc/examples/autotools
          - name: server-conf
            mountPath: /server-conf
      volumes:
        - name: bst-repo
          emptyDir: {}
        - name: server-conf
          configMap:
            name: bst-server
      restartPolicy: Never
  backoffLimit: 0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bst-server
  namespace: buildgrid
data:
  project-server.conf: |

    remote-execution:
      execution-service:
        url: http://buildgrid-stack:50051
      storage-service:
        url: http://buildgrid-stack:50051
      action-cache-service:
        url: http://buildgrid-stack:50051
