apiVersion: batch/v1
kind: Job
metadata:
  name: build-abseil
  namespace: buildgrid
spec:
  template:
    metadata:
      name: build-abseil
    spec:
      containers:
      - name: build-abseil
        image: remoteapistesting/recc-build:latest
        command: ["/bin/bash", "-c"]
        args:
         - git clone --depth=1 https://github.com/abseil/abseil-cpp.git;
           cd abseil-cpp;
           mkdir -p build;
           cd build && cmake ..;
           export RECC_SERVER="buildgrid-stack:50051";
           export RECC_INSTANCE="";
           make `CC=recc`
      restartPolicy: Never
  backoffLimit: 0
