apiVersion: batch/v1
kind: Job
metadata:
  name: build-abseil
  namespace: buildgrid
spec:
  template:
    metadata:
      name: build-abseil
    spec:
      containers:
      - name: build-abseil
        image: remoteapistesting/recc-build:latest
        command: ["/bin/bash", "-x", "-c"]
        args:
         - wget https://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz;
           tar xvf hello-2.10.tar.gz;
           cd hello-2.10;
           ./configure;
           export RECC_SERVER=buildgrid-stack:50051;
           make CC="recc cc";
           ./hello
      restartPolicy: Never
  backoffLimit: 0
