version: '3.4'
services:
  frontend:
    build:
      context: docker
      target: buildfarm
      args:
        BUILDFARM_VERSION: 1.3.0
        BAZEL_VERSION: 3.6.0 # Version of Bazel required to build Buildfarm
        BUILDFARM_DAEMON: buildfarm-server
        BUILDFARM_CONFIG: /config/server.config
    image: buildfarm_server:latest
    ports:
    - 8980:8980
    volumes:
    - ./buildfarm_config:/config
  
  worker:
    build:
      context: docker
      target: buildfarm
      args:
        BUILDFARM_VERSION: 1.3.0
        BAZEL_VERSION: 3.6.0 # Version of Bazel required to build Buildfarm
        BUILDFARM_DAEMON: buildfarm-operationqueue-worker
        BUILDFARM_CONFIG: /config/worker.config
    image: buildfarm_worker:latest
    volumes:
    - ./buildfarm_config:/config
    - ./worker:/tmp/worker
    depends_on:
    - frontend


