version: '3.4'
services:
  client:
    build:
      context: docker
      target: pants_client
    image: pants_client:latest
    command: >
      sh -c
        "git clone --branch=main https://github.com/pantsbuild/example-python.git && \
        cd example-python && \
        git checkout 2a6f66ce8a4557d4867b39accfca171d7262bb76 && \
        ./pants --no-pantsd -ldebug \
          --remote-execution \
          --remote-execution-server=frontend:8980 \
          --remote-store-server=frontend:8980 \
          --remote-instance-name=remote-execution \
          --remote-execution-extra-platform-properties=OSFamily=linux \
          test helloworld:: "
