# The contents of this file are covered by APACHE License Version 2.
# See licenses/APACHEV2-LICENSE.txt for more information.

version: '3.4'
services:
  frontend:
    build:
      context: docker
      target: buildgrid
      args:
        BUILDGRID_VERSION: 0.0.4
    command:
    - start
    - -vvv
    - /config/server.config
    image: buildgrid:latest
    restart: on-failure
    ports:
    - 8980:8980
    volumes:
    - ./buildgrid_config:/config
    depends_on:
    - database
  
  database:
    image: postgres:9.6.18
    environment:
      POSTGRES_USER: bgd
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: bgd
    ports:
      - "5432:5432"

  worker:
    build:
      context: docker
      target: buildbox
      args:
        BUILDBOX_VERSION: 0.0.13
    image: buildbox:latest
    restart: on-failure
    command:
    - --buildbox-run=buildbox-run-hosttools
    - --bots-remote=http://frontend:8980
    - --cas-remote=http://frontend:8980
    - --instance=remote-execution
    - --request-timeout=30 
    - --runner-arg=--disable-localcas
    - --platform
    - OSFamily=Linux
    depends_on:
    - frontend


