version: '3.4'
services:
  client:
    build:
      context: docker
      target: recc
      args:  
        RECC_VERSION: 0.0.40
        BUILDBOX_COMMON_VERSION: 0.0.40
        BUILDBOX_WORKER_VERSION: 0.0.39
        BUILDBOX_HOST_TOOLS_SHA: f953eb90e743e21a68a8027e721471a65670d30c
    image: recc:latest 
    environment: 
    - RECC_SERVER=frontend:8980
    - RECC_INSTANCE=remote-execution
    - RECC_REMOTE_PLATFORM_OSFamily=linux
    - CC=/recc/build/bin/recc /usr/bin/gcc 
    command: >
      sh -c
        "git clone --branch v1.1.0 https://github.com/tlsa/libcyaml.git &&
        cd libcyaml &&
        make && make test"
