version: '3.4'
services:
  client:
    build:
      context: docker
      target: recc
      args:  
        RECC_VERSION: 0.0.36
        BUILDBOX_VERSION: 0.0.21
    image: recc:latest 
    environment: 
    - RECC_SERVER=frontend:8980
    - RECC_INSTANCE=remote-execution
    - RECC_REMOTE_PLATFORM_OSFamily=Linux
    - CC=/recc/build/bin/recc /usr/bin/gcc 
    command: >
      sh -c
        "git clone --branch v1.1.0 https://github.com/tlsa/libcyaml.git &&
        cd libcyaml &&
        make && make test"