apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser
  namespace: buildbarn
spec:
  selector:
    matchLabels:
      app: browser
  template:
    metadata:
      labels:
        app: browser
    spec:
      containers:
      - image: buildbarn/bb-browser:20200102T103638Z-e432c91
        args:
        - /config/browser.jsonnet
        name: browser
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /config/browser.jsonnet
          name: config
          subPath: browser.jsonnet
        - mountPath: /config/common.libsonnet
          name: common
          subPath: common.libsonnet
      volumes:
      - configMap:
          name: browser
        name: config
      - configMap:
          name: common
        name: common
---
apiVersion: v1
kind: Service
metadata:
  name: browser
  namespace: buildbarn
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: browser
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: browser
  namespace: buildbarn
spec:
  rules:
  - host: bb-browser.example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: browser
          servicePort: 80
