apiVersion: v1
data:
  frontend.jsonnet: |
    local common = import 'common.libsonnet';

    {
      blobstore: common.blobstore,
      httpListenAddress: common.httpListenAddress,
      grpcServers: [{
        listenAddresses: [':8980'],
        authenticationPolicy: { allow: {} },
      }],
      schedulers: {
        'ubuntu16-04': { address: 'scheduler:8982' },
      },
      verifyActionResultCompleteness: true,
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
    }
kind: ConfigMap
metadata:
  name: frontend
  namespace: buildbarn
