apiVersion: v1
data:
  storage.jsonnet: |
    local common = import 'common.libsonnet';

    {
      blobstore: {
        contentAddressableStorage: {
          circular: {
            directory: '/cas',
            offsetFileSizeBytes: 16 * 1024 * 1024,
            offsetCacheSize: 10000,
            dataFileSizeBytes: 10 * 1024 * 1024 * 1024,
            dataAllocationChunkSizeBytes: 16 * 1024 * 1024,
          },
        },
        actionCache: {
          circular: {
            directory: '/ac',
            offsetFileSizeBytes: 1024 * 1024,
            offsetCacheSize: 1000,
            dataFileSizeBytes: 100 * 1024 * 1024,
            dataAllocationChunkSizeBytes: 1024 * 1024,
            instances: ['ubuntu16-04'],
          },
        },
      },
      httpListenAddress: common.httpListenAddress,
      grpcServers: [{
        listenAddresses: [':8981'],
        authenticationPolicy: { allow: {} },
      }],
      allowAcUpdatesForInstances: ['ubuntu16-04'],
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      jaeger: {
        collectorEndpoint: 'http://jaeger-collector.jaeger:14268/api/traces',
      },
    }

kind: ConfigMap
metadata:
  name: storage
  namespace: buildbarn
