apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: buildbarn
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - args:
        - /config/frontend.jsonnet
        image: remoteapistesting/bb-storage:latest
        name: storage
        ports:
        - containerPort: 8980
          protocol: TCP
        volumeMounts:
        - mountPath: /config/frontend.jsonnet
          name: config
          subPath: frontend.jsonnet
        - mountPath: /config/common.libsonnet
          name: common
          subPath: common.libsonnet
      volumes:
      - configMap:
          name: frontend
        name: config
      - configMap:
          name: common
        name: common
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
  name: frontend
  namespace: buildbarn
spec:
  ports:
  - port: 8980
    protocol: TCP
    name: grpc
  selector:
    app: frontend
  type: LoadBalancer
