apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-ubuntu16-04
  namespace: buildbarn
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
spec:
  selector:
    matchLabels:
      app: worker
      instance: ubuntu16-04
  template:
    metadata:
      labels:
        app: worker
        instance: ubuntu16-04
    spec:
      containers:
      - args:
        - /config/worker-ubuntu16-04.jsonnet
        image: remoteapistesting/bb-worker:latest
        name: worker
        volumeMounts:
        - mountPath: /config/worker-ubuntu16-04.jsonnet
          name: worker-config
          subPath: worker-ubuntu16-04.jsonnet
        - mountPath: /config/common.libsonnet
          name: common
          subPath: common.libsonnet
        - mountPath: /worker
          name: worker
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 7983
          protocol: TCP
      - args:
        - /config/runner-ubuntu16-04.jsonnet
        image: buildbarn/bb-runner-ubuntu16-04:20200102T102244Z-300a067
        name: runner
        volumeMounts:
        - mountPath: /config/runner-ubuntu16-04.jsonnet
          name: runner-config
          subPath: runner-ubuntu16-04.jsonnet
        - mountPath: /config/common.libsonnet
          name: common
          subPath: common.libsonnet
        - mountPath: /worker
          name: worker
      initContainers:
      - name: volume-init
        image: busybox:1.30.1
        command:
        - sh
        - -c
        - mkdir -pm 0777 /worker/build && mkdir -pm 0700 /worker/cache && chmod 0777 /worker
        volumeMounts:
        - mountPath: /worker
          name: worker
      volumes:
      - configMap:
          name: worker-ubuntu16-04
        name: worker-config
      - configMap:
          name: runner-ubuntu16-04
        name: runner-config
      - configMap:
          name: common
        name: common
      - emptyDir: {}
        name: worker
