apiVersion: batch/v1
kind: Job
metadata:
  name: build-abseil
  namespace: buildfarm
spec:
  template:
    metadata:
      name: build-abseil
    spec:
      containers:
      - name: build-abseil
        image: remoteapistesting/bazel-build:latest
        command:
         - /bin/bash
         - -c
         - /bin/bazel-build-wrapper https://github.com/abseil/abseil-cpp master --remote_executor=grpc://buildfarm-server //absl/...
      restartPolicy: Never
  backoffLimit: 0
