#!/bin/bash

# First argument is the git repo to build with Bazel
git_repo=$1
git_ref=$2
# All the remaining arguments will be passed to `bazel build`
bazel_args="${@:3}"
bazel_target="${@: -1}"

echo "## bazelrc file:"
cat bazelrc
echo "## end of bazelrc\n"

git clone $git_repo repo
cd repo
git checkout $git_ref

sed -i 's/\(zip -qd $@\)/chmod +w $@ \&\& \1/' third_party/BUILD

# Rename bazel_toolchains if present
if grep "bazel_toolchains" WORKSPACE; then
  sed -i -e 's/"bazel_toolchains"/"bazel_toolchains_old"/' WORKSPACE
  ## Append toolchain to the workspace
  export WORKSPACEFILE=$(printf "%q" "$(cat /src/workspace)" | sed -e s/\'//g |sed -e 's/\$//')
  sed -ine "/^load(\"@bazel_toolchains/i ${WORKSPACEFILE}\n" WORKSPACE
else
  cat /src/workspace >> WORKSPACE
fi

echo "## WORKSPACE file:"
cat WORKSPACE
echo "## end of WORKSPACE\n"

# Execute bazel build
set -x

echo "Attempting to fetch target:"
echo $bazel_target

for i in {0..10}
    do
        bazel fetch $bazel_target && break
    done

bazel --bazelrc=/src/bazelrc build $bazel_args
